version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
  redis:
    image: "redis:alpine"
  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DEBUG=true

      - DB_USER=
      - DB_PASS=
      - DB_NAME="hiiop_dev"
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
