* op-100

** TODO Overview

** Setup

   To get an interactive development environment run:

   #+BEGIN_EXAMPLE
   lein figwheel
   #+END_EXAMPLE
   
   and open your browser at [[http://localhost:3449/][localhost:3449]].
   This will auto compile and send all changes to the browser without the
   need to reload. After the compilation process is complete, you will
   get a Browser Connected REPL. An easy way to try it is:
   
   #+BEGIN_EXAMPLE
   (js/alert "Am I connected?")
   #+END_EXAMPLE
   
   and you should see an alert in the browser window.

   To clean all compiled files:

   #+BEGIN_EXAMPLE
   lein clean   
   #+END_EXAMPLE

   To create a production build run:
   
   #+BEGIN_EXAMPLE
   lein do clean
   cljsbuild once min   
   #+END_EXAMPLE

   And open your browser in `resources/public/index.html`. You will not
   get live reloading, nor a REPL. 

** Migrations
   Manage migrations with the following commands (prepend =lein
   migratus=):
   | Command       | Description                       |
   |---------------+-----------------------------------|
   | migrate       | apply migrations                  |
   | rollback      | run "down" for previous migration |
   | create <name> | create new migration              |

   [[https://github.com/yogthos/migratus][more about migratus]]

  
** TODO License

