CREATE TABLE users
(id VARCHAR(36) PRIMARY KEY,
 name VARCHAR(300) DEFAULT NULL,
 email VARCHAR(100) UNIQUE,
 moderator BOOLEAN DEFAULT false,
 last_login TIME,
 is_active BOOLEAN DEFAULT false,
 pass TEXT DEFAULT NULL);
